app = '5-stacks'
primary_region = 'sjc'
console_command = 'php /var/www/html/artisan tinker'

[deploy]
strategy = 'immediate'

[env]
APP_ENV = 'production'

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[[statics]]
guest_path = 'public/build'
url_prefix = 'build'
